### ISSUE TITLE
Checksum Error

### ISSUE THREAD

**Issue by TomTom876** [OpenAPITools/openapi-generator-bazel#24]
In WORKSPACE, I have:
```
http_archive(
    name = "openapi_tools_generator_bazel",
    sha256 = "c6e4c253f1ae0fbe4d4ded8a719f6647273141d0dc3c0cd8bb074aa7fc3c8d1c",
    urls = ["https://github.com/OpenAPITools/openapi-generator-bazel/releases/download/0.1.5/openapi-tools-generator-bazel-0.1.5.tar.gz"],
)

load("@openapi_tools_generator_bazel//:defs.bzl", "openapi_tools_generator_bazel_repositories")

openapi_tools_generator_bazel_repositories(
    openapi_generator_cli_version = "5.1.0",
)
```
In BUILD.bazel, I have:
```
load("@openapi_tools_generator_bazel//:defs.bzl", "openapi_generator")

openapi_generator(
    name = "common-code-gen",
    generator = "spring",
    spec = "common-rest.yaml",
)
```
When doing bazel build, I got this error. Thanks for help
```
ERROR: An error occurred during the fetch of repository 'openapi_tools_generator_bazel_cli':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_damuliu/db5682bae04dc3823c8e24726260b427/external/bazel_tools/tools/build_defs/repo/jvm.bzl", line 109, column 28, in _jvm_import_external
                repository_ctx.download(
Error in download: java.io.IOException: Error downloading [https://jcenter.bintray.com/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar, https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar] to /private/var/tmp/_bazel_damuliu/db5682bae04dc3823c8e24726260b427/external/openapi_tools_generator_bazel_cli/openapi-generator-cli-5.3.0.jar: Checksum was f29d9d715a0d67cf1457d918ae7ed33f02d7fb2730c018d246a8d4a93d5ba7e1 but wanted e4e45d5441283b2f0f4bf988d02186b85425e7b708b4be0b06e3bfd7c7aa52c7
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_damuliu/db5682bae04dc3823c8e24726260b427/external/bazel_tools/tools/build_defs/repo/jvm.bzl", line 109, column 28, in _jvm_import_external
                repository_ctx.download(
Error in download: java.io.IOException: Error downloading [https://jcenter.bintray.com/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar, https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar] to /private/var/tmp/_bazel_damuliu/db5682bae04dc3823c8e24726260b427/external/openapi_tools_generator_bazel_cli/openapi-generator-cli-5.3.0.jar: Checksum was f29d9d715a0d67cf1457d918ae7ed33f02d7fb2730c018d246a8d4a93d5ba7e1 but wanted e4e45d5441283b2f0f4bf988d02186b85425e7b708b4be0b06e3bfd7c7aa52c7
ERROR: /Users/damuliu/eclipse-workspace/tcx/WORKSPACE:174:43: //external:openapi_tools_generator_bazel/dependency/openapi-generator-cli depends on @openapi_tools_generator_bazel_cli//jar:jar in repository @openapi_tools_generator_bazel_cli which failed to fetch. no such package '@openapi_tools_generator_bazel_cli//jar': java.io.IOException: Error downloading [https://jcenter.bintray.com/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar, https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar] to /private/var/tmp/_bazel_damuliu/db5682bae04dc3823c8e24726260b427/external/openapi_tools_generator_bazel_cli/openapi-generator-cli-5.3.0.jar: Checksum was f29d9d715a0d67cf1457d918ae7ed33f02d7fb2730c018d246a8d4a93d5ba7e1 but wanted e4e45d5441283b2f0f4bf988d02186b85425e7b708b4be0b06e3bfd7c7aa52c7
ERROR: Analysis of target '//admin-service/common:common-code-gen' failed; build aborted: Analysis failed
INFO: Elapsed time: 64.264s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (18 packages loaded, 338 targets configured)
```

**Comment by ethanrcohen** [comment]
The instructions need to be updated -- the openapi_tools_generator_bazel_repositories macro takes a SHA256 hash, which you need to provide if you are specifying a different CLI version than the default, see https://github.com/OpenAPITools/openapi-generator-bazel/blob/master/internal/openapi_generator.bzl#L5. 

Try updating your code to 

`
openapi_tools_generator_bazel_repositories(
    openapi_generator_cli_version = "5.1.0",
    sha256="f29d9d715a0d67cf1457d918ae7ed33f02d7fb2730c018d246a8d4a93d5ba7e1"
)`

**Comment by TomTom876** [comment]
Thanks @ethanrcohen, I finally got it passed the checksum issue, with a minor change to your suggestion on the sha256 value:
openapi_tools_generator_bazel_repositories( openapi_generator_cli_version = "5.1.0", sha256="62f9842f0fcd91e4afeafc33f19a7af41f2927c7472c601310cedfc72ff1bb19" )
